name: Cart Java $(Build.DefinitionName)_$(SourceBranchName)$(Rev:.r)

trigger:
  batch: true
  branches:
    include:
      - develop
      - main

pr:
  branches:
    include:
      - develop
      - main

variables:
  - name: tag
    value: "$(Build.BuildId)"
  - name: mvn_goal
    # TODO NW-3748 Include develop here, to deploy snapshot builds?
    ${{ if eq(variables['Build.SourceBranchName'], 'main' ) }}:
      value: 'clean deploy'
    ${{ else }}:
      value: 'clean verify'

pool: PB Scalable Build Pool

stages:
  - stage: Build
    jobs:
      - job: Build
        # TODO NW-3748 90 minutes is a LONG timeout.
        timeoutInMinutes: 90
        workspace:
          clean: all
        variables:
          MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
          MAVEN_OPTS: "-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)"

        steps:
          - task: Cache@2
            inputs:
              key: 'maven | "$(Agent.OS)" | pom.xml'
              restoreKeys: |
                maven | "$(Agent.OS)"
                maven
              path: $(MAVEN_CACHE_FOLDER)
            displayName: Cache Maven local repo

          - bash: |
              echo "$(CCCS_GPG_SECRET_KEY)" | base64 -d  | gpg --import --batch --pinentry-mode loopback
            displayName: "Import GPG Secret Key"
            name: import
            env:
              CCCS_GPG_SECRET_KEY: $(cccs_gpg_secret_key)

          - task: Maven@4
            displayName: "Build project with maven"
            env:
              CCCS_GPG_KEY: $(cccs_gpg_key)
              DEPLOY_TOKEN: $(deploy_token)
            inputs:
              mavenVersionOption: "Path"
              mavenDirectory: "/opt/maven3/"
              mavenSetM2Home: true
              mavenAuthenticateFeed: true
              skipEffectivePom: true
              mavenPomFile: "pom.xml"
              mavenOptions: "$(MAVEN_OPTS)"
              javaHomeOption: "Path"
              jdkDirectory: "/opt/java11"
              publishJUnitResults: true
              testResultsFiles: "**/surefire-reports/TEST-*.xml"
              goals: "$(mvn_goal)"
              # TODO NW-3748 We don't really need/want these options for non-deploy builds, but it might be easier to just set them all the time.
              options: "-s deploy-settings.xml -DDEPLOY_TOKEN=\"$(DEPLOY_TOKEN)\" -Dgpg.skip=false -Dgpg.passphrase=\"$(CCCS_GPG_KEY)\""
